source 'https://github.com/Cocoapods/Specs.git'
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'Drizzling' do
 pod 'SwiftyJSON'
 pod 'Alamofire', '~> 4.5'
 pod 'Kingfisher', '~> 4.0'
 pod 'ObjectMapper', '~> 3.0.0'
 pod 'RxSwift', '~> 4.0'
 pod 'RxCocoa', '~> 4.0'
end
