# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.30.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    carthage
  end

  lane :archive do |options| 
   increment_build_number(
        build_number: latest_testflight_build_number({
            version: options[:version_number]
        }) + 1,
    )
    gym(
      scheme: "Drizzling",
      output_directory:"build",
      output_name: "drizzling.ipa"
    )
  end


   lane :testFlight do
      archive
      pilot(
        ipa:"build/drizzling.ipa",
        username: "123qaz456wsx78@sina.cn",
        skip_waiting_for_build_processing: true
    )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
